Franka1: # This is the robot name
  name: "franka_xhand" # this is used for retrieval articulation cfg
  type: "dexterous"
  common:
    # Initial position range (relative to environment offset)
    initial_pos_range: [0, 0, 1.0, 0, 0, 1.0]  # Format: [x_min, y_min, z_min, x_max, y_max, z_max]
    # Initial orientation range
    initial_ori_range: [0, 0 , 0, 0, 0, 0]  # [min_rx, min_ry, min_rz, max_rx, max_ry, max_rz]
    # Initial joint position for the robot
    initial_joint_pos: {
      "panda_joint1": 0.0,
      "panda_joint2": -0.785,
      "panda_joint3": 0.0,
      "panda_joint4": -2.356,
      "panda_joint5": 0.0,
      "panda_joint6": 1.571,
      "panda_joint7": 0.785,
      "right_hand_thumb_rota_joint1": 0.0,
      "right_hand_thumb_rota_joint2": 0.0,
      "right_hand_thumb_bend_joint": 0.0,
      "right_hand_index_bend_joint": 0.0,
      "right_hand_index_joint1": 0.0,
      "right_hand_index_joint2": 0.0,
      "right_hand_mid_joint1": 0.0,
      "right_hand_mid_joint2": 0.0,
      "right_hand_ring_joint1": 0.0,
      "right_hand_ring_joint2": 0.0,
      "right_hand_pinky_joint1": 0.0,
      "right_hand_pinky_joint2": 0.0,
    }

  action: # This is used for action manager
    base_action: null
    arm_action: ik_abs # ik_abs, joint_pos (FrankaXhand has no ik_curobo term)
    eef_action: joint_pos # joint_pos for dexterous hand

  planner:
    ik:
      type: "franka_xhand"
      enable: true
      ik_num_instances: 2
      ik_batch_size: 8
      ik_num_seeds: 20
      ik_position_threshold: 0.005
      ik_rotation_threshold: 0.05
      microbatch_wait_ms: 1000.0
      debug: true
    motiongen:
      type: "franka_xhand"
      enable: true
      batch_size: 8
      debug: true
      motiongen_num_instances: 1
      microbatch_wait_ms: 1000.0
      mode: position
    arm:
      type: "default"
      mode: position
    eef:
      type: "default"
